export const stitchRegistry = {
  customerHome: "customer_home",
  search_filters: "search_filters",
  shop_availability_alternatives: "shop_availability_alternatives",
  search: "search_filter",
  searchMap: "search_map_view",
  orderConfirmed: "order_confirmation_success",
  notifications: "same_additiona_scrrens/notifications_complaints",
  subscriptions: "subscription_plans",
  subscription_loyalty_shop: "subscription_loyalty_shop",
  rewards: "referrals_loyalty",
  reportIssue: "report_issue",
  shopAnalytics: "shop_analytics",
  shopPromotions: "promotions_loyalty",
  shopDelivery: "delivery_management_tracking",
  live_order_tracking: "same_additiona_scrrens/live_order_tracking",
  deliveryDashboard: "delivery_mode_dashboard_3",
  deliveryTrip: "delivery_active_trip",
  deliveryOtp: "delivery_otp_verification",
  deliveryComplete: "failed_delivery_reschedule",
  cancel_order: "cancel_order",
  cancel_order_reason: "cancel_order_reason",
  customer_management_shop: "customer_management_shop",
  customer_subscription_plans: "customer_subscription_plans",
  emergency_help: "emergency_help",
  inventory_management: "inventory_management",
  manual_order_entry: "manual_order_entry",
  onboarding_slide_1: "onboarding_slide_1",
  onboarding_slide_2: "onboarding_slide_2",
  onboarding_slide_3: "onboarding_slide_3",
  order_summary: "order_summary",
  order_confirmation: "same_additiona_scrrens/order_confirmation",
  order_history: "same_additiona_scrrens/order_history",
  shop_dashboard_home_1: "shop_dashboard_home_1",
  shop_settings_profile: "shop_settings_profile",
  shop_vendor_registration_1: "shop_vendor_registration_1",
  shop_vendor_registration_2: "shop_vendor_registration_2",
  splash_screen: "splash_screen",
  customer_profile: "same_additiona_scrrens/customer_profile",
  rate_review_customer: "same_additiona_scrrens/rate_review_customer",
  schedule_delivery: "same_additiona_scrrens/schedule_delivery",
  shop_earnings: "shop_earnings",
} as const;

export function getStitchAssetPath(screen: keyof typeof stitchRegistry) {
  return `specs/stitch_final/${stitchRegistry[screen]}`;
}
