import express from "express";
import academicYearRoutes from "./academicYear.routes.js";
import bankRoutes from "./bank.routes.js";
import bindingTypeRoutes from "./bindingType.routes.js";
import bookRoutes from "./book.routes.js";
import bookMediumRoutes from "./bookMedium.routes.js";
import bookStandardRoutes from "./bookStandard.routes.js";
import bookSyllabusRoutes from "./bookSyllabus.routes.js";
import bookTermRoutes from "./bookTerm.routes.js";
import defectCategoryRoutes from "./defectCategory.routes.js";
import defectSubCategoryRoutes from "./defectSubCategory.routes.js";
import defectTypeRoutes from "./defectType.routes.js";
import deliveryPointRoutes from "./deliveryPoint.routes.js";
import departmentRoutes from "./department.routes.js";
import designationRoutes from "./designation.routes.js";
import districtRoutes from "./district.routes.js";
import editionTypeRoutes from "./editionType.routes.js";
import errorCategoryRoutes from "./errorCategory.routes.js";
import errorSubCategoryRoutes from "./errorSubCategory.routes.js";
import errorTypeRoutes from "./errorType.routes.js";
import godownRoutes from "./godown.routes.js";
import indentingDepartmentRoutes from "./indentingDepartment.routes.js";
import machineCategoryRoutes from "./machineCategory.routes.js";
import organizationRoutes from "./organization.routes.js";
import paperTypeRoutes from "./paperType.routes.js";
import printerRoutes from "./printer.routes.js";
import printerBankRoutes from "./printerBank.routes.js";
import printerCommercialDetailRoutes from "./printerCommercialDetail.routes.js";
import printerContactRoutes from "./printerContact.routes.js";
import printerDocumentTypeRoutes from "./printerDocumentType.routes.js";
import printerTechnicalDetailRoutes from "./printerTechnicalDetail.routes.js";
import printerTypeRoutes from "./printerType.routes.js";
import printingFlowRoutes from "./printingFlow.routes.js";
import printingTypeRoutes from "./printingType.routes.js";
import roleRoutes from "./role.routes.js";
import subDistrictRoutes from "./subDistrict.routes.js";
import transportationRateRoutes from "./transportationRate.routes.js";
import transportationTypeRoutes from "./transportationType.routes.js";
import userRoutes from "./user.routes.js";
import vehicleTypeRoutes from "./vehicleType.routes.js";
import workflowRoutes from "./workflow.routes.js";
import workflowProcessRoutes from "./workflowProcess.routes.js";

const router = express.Router();

router.use("/academic-years", academicYearRoutes);
router.use("/banks", bankRoutes);
router.use("/binding-types", bindingTypeRoutes);
router.use("/books", bookRoutes);
router.use("/book-mediums", bookMediumRoutes);
router.use("/book-standards", bookStandardRoutes);
router.use("/book-syllabuses", bookSyllabusRoutes);
router.use("/book-terms", bookTermRoutes);
router.use("/defect-categories", defectCategoryRoutes);
router.use("/defect-sub-categories", defectSubCategoryRoutes);
router.use("/defect-types", defectTypeRoutes);
router.use("/delivery-points", deliveryPointRoutes);
router.use("/departments", departmentRoutes);
router.use("/designations", designationRoutes);
router.use("/districts", districtRoutes);
router.use("/edition-types", editionTypeRoutes);
router.use("/error-categories", errorCategoryRoutes);
router.use("/error-sub-categories", errorSubCategoryRoutes);
router.use("/error-types", errorTypeRoutes);
router.use("/godowns", godownRoutes);
router.use("/indenting-departments", indentingDepartmentRoutes);
router.use("/machine-categories", machineCategoryRoutes);
router.use("/organizations", organizationRoutes);
router.use("/paper-types", paperTypeRoutes);
router.use("/printers", printerRoutes);
router.use("/printer-banks", printerBankRoutes);
router.use("/printer-commercial-details", printerCommercialDetailRoutes);
router.use("/printer-contacts", printerContactRoutes);
router.use("/printer-document-types", printerDocumentTypeRoutes);
router.use("/printer-technical-details", printerTechnicalDetailRoutes);
router.use("/printer-types", printerTypeRoutes);
router.use("/printing-flows", printingFlowRoutes);
router.use("/printing-types", printingTypeRoutes);
router.use("/roles", roleRoutes);
router.use("/sub-districts", subDistrictRoutes);
router.use("/transportation-rates", transportationRateRoutes);
router.use("/transportation-types", transportationTypeRoutes);
router.use("/users", userRoutes);
router.use("/vehicle-types", vehicleTypeRoutes);
router.use("/workflow-master", workflowRoutes);
router.use("/workflow", workflowProcessRoutes);

export default router;
